### ISSUE TITLE
hashTag Keep following the same batch of users

### ISSUE THREAD

**Issue by tsejerome** [nikilkumar9/InstaBot#6]
This is related to hashtag based python script.

I used it on my ac and realized that everytime we updated the tag on the hashtag list.

After renewing the tag, the bot did actually go through all the new post with the new tagging.

But in terms of the "user following" part, the bot only did go through the same set of users over and over again.

Not new users was add into the queue, and at last there is no difference between the following count initially and at last.

Please tell me if I can do anything to help on this.

**Comment by nikilkumar9** [comment]
Hi Jerome, 

The code has been updated and tested to an extent on my local desktop. Please git pull and check if it the issue is solved or not. It should work.

If not, open another issue with screenshots of the output too.
