### ISSUE TITLE
[User Based Following] Incable of crewing through the user's follower list

### ISSUE THREAD

**Issue by felixfong227** [nikilkumar9/InstaBot#7]
InstaBot version: d2e8de11c87070bb9aff247297dbf011dc08cbad
Python version: Python 3.7.2
---

After the initial network fetch for the first batch of the user's followers and rendered into the modal(say only for 10 to 15 results prefetch) but the total number of followers for that original user is 10K+, so the count doesn't add up at the end result

**Comment by nikilkumar9** [comment]
Hi Felix, please take a look at the new changes (commit: 3a718934a61a4598d155cc224ca2f73ccfc1f3e4) to the userFollowersBased_follow and unfollow scripts. The changes should have solved your problem. 

Please open another issue with further details, if the problem still persists. Thanks!
